backend:
  name: github
  repo: sulenchy/portfolio
  branch: master
  base_url: http://127.0.0.1:5501
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  # 🙋 ABOUT ME COLLECTION
  - name: "about"
    label: "About Me"
    files:
      - file: "public/content/about.json"
        label: "About Me"
        name: "about"
        fields:
          - { label: "Greeting", name: "greeting", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Avatar", name: "avatar", widget: "image" }
          - { label: "BgImage", name: "bgImage", widget: "image" }

  # 🧱 PROJECTS COLLECTION
  - name: "projects"
    label: "Projects"
    files:
      - file: "public/content/projects.json"
        label: "Projects"
        name: "projects"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Project Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Skills Demonstrated"
                name: "skillDemonstrated"
                widget: "list"
                field: { label: "Skill", name: "skill", widget: "string" }
              - label: "Languages"
                name: "languages"
                widget: "list"
                field: { label: "Language", name: "language", widget: "string" }
              - { label: "Is Deployed?", name: "isDeployed", widget: "boolean", default: false }
              - label: "Links"
                name: "links"
                widget: "object"
                fields:
                  - label: "GitHub"
                    name: "github"
                    widget: "object"
                    fields:
                      - label: "Type"
                        name: "githubType"
                        widget: "select"
                        options: ["Public", "Private"]
                      - { label: "GitHub Link", name: "link", widget: "string" }
                  - { label: "Deployed URL", name: "deployed", widget: "string" }

  # ⚙️ SKILLS COLLECTION
  - name: "skills"
    label: "Skills"
    files:
      - file: "public/content/skills.json"
        label: "Skills"
        name: "skills"
        fields:
          - label: "Skills"
            name: "skills"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Skill Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Years of Experience", name: "yearsOfExperience", widget: "number", min: 0 }

  # 💼 EXPERIENCE COLLECTION
  - name: "experience"
    label: "Experience"
    files:
      - file: "public/content/experience.json"
        label: "Experience"
        name: "experience"
        fields:
          - label: "Experience"
            name: "experience"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Company Name", name: "companyName", widget: "string" }
              - label: "Skills Demonstrated"
                name: "skillsDemonstrated"
                widget: "list"
                field: { label: "Skill", name: "skill", widget: "string" }
              - { label: "Achievement", name: "achievement", widget: "text" }
              - { label: "Start Date", name: "startDate", widget: "datetime", format: "YYYY-MM-DD" }
              - { label: "End Date", name: "endDate", widget: "datetime", format: "YYYY-MM-DD" }
              - label: "Links"
                name: "links"
                widget: "list"
                field:
                  { label: "Link", name: "link", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }